name: Docker build
description: Build and push Docker image
inputs:
  image_name:
    description: Image name
    default: ${{ github.repository }}
  build_number:
    description: Build number for tagging the image
    required: true
  context_path:
    description: Path to folder with Dockerfile
    default: .
  platforms:
    description: List of target platforms (e.g., linux/amd64,linux/arm64)
    default: linux/amd64
  push:
    description: Whether to push the image to registry
    default: 'false'
  registry_url:
    description: Docker registry URL
    default: docker.io
  registry_username:
    description: Username for Docker registry
  registry_token:
    description: Token for Docker registry
runs:
  using: composite
  steps:
    - run: bash ./docker/docker.sh
      env:
        IMAGE_NAME: ${{ inputs.image_name }}
        BUILD_NUMBER: ${{ inputs.build_number }}
        CONTEXT_PATH: ${{ inputs.context_path }}
        PLATFORMS: ${{ inputs.platforms }}
        PUSH: ${{ inputs.push }}
        REGISTRY_URL: ${{ inputs.registry_url }}
        REGISTRY_USERNAME: ${{ inputs.registry_username }}
        REGISTRY_TOKEN: ${{ inputs.registry_token }}
      shell: bash
