name: Build name
description: Creates the build name depending on the parameters
outputs:
  build-name:
    description: Build name
    value: ${{ steps.build-name.outputs.build-name }}
runs:
  using: composite
  steps:
    - name: Set build name to env and output
      id: build-name
      shell: bash
      run: |
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          echo "BUILD_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "build-name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
          sha=${GITHUB_SHA::7}
          echo "BUILD_NAME=$sha" >> $GITHUB_ENV
          echo "build-name=$sha" >> $GITHUB_OUTPUT
        fi
